const API_BASE = 'http://127.0.0.1:5000';
const DEMO_ZONES = [
  { id:'SKM-04', name:'North Sikkim Â· Zone 04', state:'Sikkim', lat:27.53, lon:88.52, slope:78, historicalRisk:82, rainfall:89, sevenDayRainfall:74, soilMoisture:81, groundMovement:62, population:3240, level:'critical', recommendation:'Avoid the identified road section and initiate a field inspection.' },
  { id:'SKM-01', name:'East Sikkim Â· Zone 01', state:'Sikkim', lat:27.31, lon:88.61, slope:69, historicalRisk:73, rainfall:62, sevenDayRainfall:68, soilMoisture:71, groundMovement:38, population:1840, level:'high', recommendation:'Monitor slope movement and keep local response teams on standby.' },
  { id:'ASM-02', name:'Dima Hasao Â· Zone 02', state:'Assam', lat:25.50, lon:93.02, slope:64, historicalRisk:66, rainfall:56, sevenDayRainfall:51, soilMoisture:64, groundMovement:35, population:2180, level:'high', recommendation:'Inspect vulnerable road cuts before the next rainfall window.' },
  { id:'ARU-03', name:'West Siang Â· Zone 03', state:'Arunachal Pradesh', lat:28.10, lon:94.80, slope:58, historicalRisk:61, rainfall:52, sevenDayRainfall:49, soilMoisture:57, groundMovement:30, population:990, level:'moderate', recommendation:'Keep community channels open and monitor rainfall accumulation.' },
  { id:'MEG-02', name:'East Khasi Hills Â· Zone 02', state:'Meghalaya', lat:25.56, lon:91.88, slope:55, historicalRisk:57, rainfall:63, sevenDayRainfall:55, soilMoisture:60, groundMovement:31, population:2760, level:'high', recommendation:'Use caution around saturated slopes and report new cracks.' },
  { id:'NAG-01', name:'Kohima Â· Zone 01', state:'Nagaland', lat:25.67, lon:94.11, slope:45, historicalRisk:48, rainfall:38, sevenDayRainfall:42, soilMoisture:45, groundMovement:21, population:1250, level:'moderate', recommendation:'No immediate action. Continue normal monitoring.' },
  { id:'MAN-02', name:'Churachandpur Â· Zone 02', state:'Manipur', lat:24.33, lon:93.67, slope:39, historicalRisk:42, rainfall:31, sevenDayRainfall:34, soilMoisture:39, groundMovement:18, population:820, level:'low', recommendation:'No immediate action. Continue normal monitoring.' },
  { id:'MIZ-01', name:'Aizawl Â· Zone 01', state:'Mizoram', lat:23.73, lon:92.72, slope:51, historicalRisk:54, rainfall:42, sevenDayRainfall:44, soilMoisture:48, groundMovement:26, population:1430, level:'moderate', recommendation:'Monitor steep road sections during heavy rainfall.' },
  { id:'TRP-01', name:'Dhalai Â· Zone 01', state:'Tripura', lat:23.98, lon:91.85, slope:32, historicalRisk:35, rainfall:26, sevenDayRainfall:32, soilMoisture:35, groundMovement:15, population:670, level:'low', recommendation:'No immediate action. Continue normal monitoring.' },
  { id:'HP-01', name:'Kullu Â· Zone 01', state:'Himachal Pradesh', lat:31.96, lon:77.10, slope:73, historicalRisk:77, rainfall:48, sevenDayRainfall:52, soilMoisture:60, groundMovement:41, population:1940, level:'high', recommendation:'Inspect known high-risk road sections.' },
  { id:'UK-01', name:'Chamoli Â· Zone 01', state:'Uttarakhand', lat:30.40, lon:79.32, slope:70, historicalRisk:74, rainfall:39, sevenDayRainfall:45, soilMoisture:52, groundMovement:36, population:1320, level:'moderate', recommendation:'Monitor known slope instability areas.' }
];
const DEMO_ALERTS = [
  { zone:'North Sikkim Â· Zone 04', detail:'Critical risk Â· NH-310A road exposure', time:'12 min ago', level:'critical' },
  { zone:'East Khasi Hills Â· Zone 02', detail:'Heavy rainfall Â· field check recommended', time:'34 min ago', level:'high' },
  { zone:'Dima Hasao Â· Zone 02', detail:'Road-side saturation Â· monitor closely', time:'1 hr ago', level:'high' }
];
const FACTOR_META = [['Intense rainfall','rainfall'],['Saturated terrain','soilMoisture'],['High slope','slope'],['Historical landslides','historicalRisk'],['Ground movement','groundMovement']];
const NORTH_EAST_STATES = new Set(['Sikkim','Assam','Arunachal Pradesh','Meghalaya','Nagaland','Manipur','Mizoram','Tripura']);
const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
let zones = [...DEMO_ZONES], alerts = [...DEMO_ALERTS], reports = [], selectedZone = zones[0], map, markerLayer, riskAreaLayer, userLocationLayer, mapLabelLayer, riskChart, liveMode = false, mapRiskFilter = 'all';
async function requestJson(url, options = {}){ const controller=new AbortController(); const timeout=setTimeout(()=>controller.abort(),5000); try { const response=await fetch(url,{...options,signal:controller.signal}); return response; } finally { clearTimeout(timeout); } }
const API = {
  async getZones(){ try { const response = await requestJson(`${API_BASE}/api/zones`); if(!response.ok) throw new Error(); const value = await response.json(); if(value.length) { liveMode = true; return value; } } catch {} liveMode = false; return DEMO_ZONES; },
  async getAlerts(){ try { const response = await requestJson(`${API_BASE}/api/alerts`); if(!response.ok) throw new Error(); return await response.json(); } catch { return DEMO_ALERTS; } },
  async getReports(){ if(liveMode) { try { const response = await requestJson(`${API_BASE}/api/reports`); if(response.ok) return await response.json(); } catch {} } try { return JSON.parse(localStorage.getItem('landsafe-reports') || '[]'); } catch { return []; } },
  async saveReport(report){ if(liveMode) { const response = await requestJson(`${API_BASE}/api/reports`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(report) }); if(!response.ok) throw new Error(); return response.json(); } const saved = await this.getReports(); saved.unshift(report); localStorage.setItem('landsafe-reports', JSON.stringify(saved)); return report; },
  async calculateRisk(zone){ const weights={rainfall:.30,sevenDayRainfall:.20,slope:.15,historicalRisk:.15,soilMoisture:.10,groundMovement:.10}; const score=Math.round(Object.entries(weights).reduce((sum,[key,weight])=>sum+Number(zone[key]||0)*weight,0)); return {score,level:score<=30?'low':score<=50?'moderate':score<=70?'high':'critical'}; }
};
function levelLabel(value){ return value.toUpperCase(); }
function formatNumber(value){ return Number(value).toLocaleString('en-IN'); }
function estimateRisk(zone){ return Math.round(Number(zone.rainfall||0)*.30+Number(zone.sevenDayRainfall||0)*.20+Number(zone.slope||0)*.15+Number(zone.historicalRisk||0)*.15+Number(zone.soilMoisture||0)*.10+Number(zone.groundMovement||0)*.10); }
function buildMetrics(data, currentReports){ const counts={critical:0,high:0,moderate:0,low:0}; data.forEach(zone=>counts[zone.level || 'moderate']++); const cards=[['Critical zones',counts.critical,'+2 this week','â†‘','#c9524b','#fff0ee','â—‰'],['High-risk zones',counts.high,'+3 this week','â†‘','#da8d32','#fff5e8','â—’'],['Active alerts',alerts.length,'2 need action','â€¢','#c6a136','#fff9df','â™§'],['Citizen reports',currentReports.length+11,'4 unverified','â€¢','#4e9d70','#eaf7ee','â–£']]; $('#metricGrid').innerHTML=cards.map(([label,value,foot,trend,color,bg,icon])=>`<div class="metric-card" style="--metric-color:${color};--metric-bg:${bg}"><div class="metric-top"><span>${label}</span><span class="metric-icon">${icon}</span></div><div class="metric-value">${value}</div><div class="metric-foot"><strong>${trend}</strong> ${foot.replace(trend,'')}</div></div>`).join(''); }
function initMap(){
  if(typeof L==='undefined'){ $('#riskMap').innerHTML='<div class="map-fallback">Map unavailable offline.<br><strong>Leaflet could not be loaded.</strong></div>'; return; }
  const northEastBounds=[[21.5,88.0],[29.8,97.8]];
  map=L.map('riskMap',{zoomControl:false,scrollWheelZoom:false,maxBounds:northEastBounds,maxBoundsViscosity:.9,minZoom:6}).fitBounds(northEastBounds,{padding:[12,12]});
  [['countryMaskPane',300],['stateBoundaryPane',400],['stateLabelPane',650],['riskMarkerPane',700],['locationPane',710]].forEach(([name,zIndex])=>{map.createPane(name);map.getPane(name).style.zIndex=zIndex;});
  L.control.zoom({position:'topright'}).addTo(map);
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'Â© OpenStreetMap contributors',maxZoom:19}).addTo(map);
  loadNorthEastIndiaBoundary();
  const legend=L.control({position:'topleft'});
  legend.onAdd=()=>{const div=L.DomUtil.create('div','risk-map-legend'); div.innerHTML='<strong>Risk level</strong><button type="button" data-risk="all">All points</button><button type="button" data-risk="critical"><i class="legend-swatch critical"></i>Critical</button><button type="button" data-risk="high"><i class="legend-swatch high"></i>High</button><button type="button" data-risk="moderate"><i class="legend-swatch moderate"></i>Moderate</button><button type="button" data-risk="low"><i class="legend-swatch low"></i>Low</button>'; div.querySelectorAll('[data-risk]').forEach(button=>button.addEventListener('click',()=>{div.querySelectorAll('[data-risk]').forEach(item=>item.classList.remove('active')); button.classList.add('active'); mapRiskFilter=button.dataset.risk; renderMarkers(mapRiskFilter);})); div.querySelector('[data-risk="all"]').classList.add('active'); L.DomEvent.disableClickPropagation(div); return div;};
  legend.addTo(map);
  markerLayer=L.layerGroup().addTo(map);
  userLocationLayer=L.layerGroup().addTo(map);
  mapLabelLayer=L.layerGroup().addTo(map);
  renderMapLabels();
  renderMarkers();
  requestAnimationFrame(()=>map.invalidateSize(true));
}
function renderMapLabels(){
  if(!mapLabelLayer)return;
  const stateCenters={'Sikkim':[27.55,88.50],'Arunachal Pradesh':[28.10,94.00],'Assam':[26.20,92.90],'Meghalaya':[25.55,91.35],'Nagaland':[26.05,94.35],'Manipur':[24.75,93.85],'Mizoram':[23.35,92.75],'Tripura':[23.75,91.70]};
  mapLabelLayer.clearLayers();
  Object.entries(stateCenters).forEach(([name,coords])=>L.marker(coords,{pane:'stateLabelPane',interactive:false,zIndexOffset:500,icon:L.divIcon({className:'map-state-label',html:`<span>${name}</span>`,iconSize:null})}).addTo(mapLabelLayer));
  const seenPlaces=new Set();
  zones.filter(zone=>NORTH_EAST_STATES.has(zone.state)).forEach(zone=>{
    const place=String(zone.name||zone.state).split(' · ')[0];
    if(seenPlaces.has(place))return;
    seenPlaces.add(place);
    L.marker([Number(zone.lat),Number(zone.lon)],{pane:'stateLabelPane',interactive:false,zIndexOffset:700,icon:L.divIcon({className:'map-place-label',html:`<span>${place}</span>`,iconSize:null})}).addTo(mapLabelLayer);
  });
}
async function loadNorthEastIndiaBoundary(){
  try{
    const response=await fetch('https://raw.githubusercontent.com/geohacker/india/master/state/india_state.geojson');
    if(!response.ok)throw new Error();
    const data=await response.json();
    const selected=data.features.filter(feature=>Object.values(feature.properties||{}).some(value=>NORTH_EAST_STATES.has(String(value))));
    if(!selected.length)return;
    const rings=[];
    const collectOuterRings=geometry=>{ if(geometry.type==='Polygon')rings.push(geometry.coordinates[0].map(([lon,lat])=>[lat,lon])); if(geometry.type==='MultiPolygon')geometry.coordinates.forEach(polygon=>rings.push(polygon[0].map(([lon,lat])=>[lat,lon]))); };
    selected.forEach(feature=>collectOuterRings(feature.geometry));
    const outer=[[20.8,87.2],[20.8,99.2],[31.2,99.2],[31.2,87.2]];
    // Keep neighboring countries visually muted, then draw the selected Indian states above the mask.
    L.polygon([outer,...rings],{pane:'countryMaskPane',color:'#f5f7f4',weight:0,fillColor:'#f5f7f4',fillOpacity:.78,fillRule:'evenodd',interactive:false}).addTo(map);
    L.geoJSON({type:'FeatureCollection',features:selected},{pane:'stateBoundaryPane',style:{color:'#176b4d',weight:2.4,fillColor:'#d9efe2',fillOpacity:.28,interactive:false}}).addTo(map);
    renderMapLabels();
    mapLabelLayer.bringToFront(); markerLayer.bringToFront(); userLocationLayer.bringToFront();
  }catch{}
}
function locateUser(){
  if(!navigator.geolocation){ showToast('Live location is not supported by this browser'); return; }
  const button=$('#locateMe');
  button.disabled=true; button.textContent='Locating…';
  navigator.geolocation.getCurrentPosition(position=>{
    const {latitude,longitude,accuracy}=position.coords;
    const withinNorthEast=latitude>=21.5&&latitude<=29.8&&longitude>=88.0&&longitude<=97.8;
    userLocationLayer.clearLayers();
    L.circleMarker([latitude,longitude],{pane:'locationPane',radius:8,color:'#1769aa',weight:3,fillColor:'#3da5f5',fillOpacity:.95}).bindTooltip(`Your live location<br>Accuracy: ±${Math.round(accuracy)} m`).addTo(userLocationLayer);
    L.circle([latitude,longitude],{pane:'locationPane',radius:accuracy,color:'#3da5f5',weight:1,fillColor:'#3da5f5',fillOpacity:.12}).addTo(userLocationLayer);
    map.setView([latitude,longitude],withinNorthEast?9:6);
    checkNearbyRisk(latitude,longitude);
    showToast(withinNorthEast?'Live location enabled on the North Eastern map':'Your location is outside the North Eastern region');
    button.disabled=false; button.textContent='⌖ My location';
  },error=>{
    const message=error.code===1?'Location permission was denied':error.code===2?'Location is unavailable':'Location request timed out';
    showToast(message); button.disabled=false; button.textContent='⌖ My location';
  },{enableHighAccuracy:true,timeout:10000,maximumAge:30000});
}
function distanceKm(lat1,lon1,lat2,lon2){ const earthRadius=6371; const radians=value=>value*Math.PI/180; const dLat=radians(lat2-lat1); const dLon=radians(lon2-lon1); const a=Math.sin(dLat/2)**2+Math.cos(radians(lat1))*Math.cos(radians(lat2))*Math.sin(dLon/2)**2; return earthRadius*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a)); }
function checkNearbyRisk(latitude,longitude){ const nearby=zones.map(zone=>{const risk=zone.riskScore||estimateRisk(zone); return {...zone,risk,distance:distanceKm(latitude,longitude,Number(zone.lat),Number(zone.lon))};}).filter(zone=>zone.distance<=25&&zone.risk>=51).sort((a,b)=>a.distance-b.distance)[0]; if(!nearby)return; const critical=nearby.risk>=71; const message=`${critical?'CRITICAL':'HIGH'} RISK NEARBY: ${nearby.name} · ${nearby.distance.toFixed(1)} km away`; L.popup({closeButton:true,autoClose:false,closeOnClick:false,className:critical?'critical-alert-popup':'high-alert-popup'}).setLatLng([latitude,longitude]).setContent(`<strong>${message}</strong><br>${nearby.recommendation||'Avoid the area and follow local safety guidance.'}`).openOn(map); showToast(message); }
function renderMarkers(filter=mapRiskFilter){ if(!markerLayer)return; markerLayer.clearLayers(); const colors={critical:'#c9524b',high:'#da8d32',moderate:'#c6a136',low:'#4e9d70'}; zones.filter(zone=>NORTH_EAST_STATES.has(zone.state)).forEach(zone=>{const risk=zone.riskScore||estimateRisk(zone); const critical=(zone.level||'moderate')==='critical'||risk>70; const riskLevel=critical?'critical':(zone.level||'moderate'); if(filter!=='all'&&riskLevel!==filter)return; const color=colors[riskLevel]||colors.moderate; const radius=(critical?9:6)+Math.min(Number(zone.population||0)/1100,10); const marker=L.circleMarker([zone.lat,zone.lon],{pane:'riskMarkerPane',radius,fillColor:color,color:'#fff',weight:critical?3:2,fillOpacity:.95,className:critical?'critical-map-point':''}); marker.bindTooltip(`<strong>${zone.name}</strong><br>${critical?'Critical point · ':''}Risk ${risk}/100`,{direction:'top'}); marker.on('click',()=>selectZone(zone)); marker.addTo(markerLayer);}); }
function renderAiPrediction(zone){
  if(!zone)return;
  const current=Number(zone.riskScore||estimateRisk(zone));
  const rainfallSignal=(Number(zone.rainfall||0)+Number(zone.sevenDayRainfall||0))/2;
  const prediction=Math.min(100,Math.max(0,Math.round(current+rainfallSignal*.08+Number(zone.groundMovement||0)*.04-4)));
  const level=prediction>70?'CRITICAL':prediction>50?'HIGH':prediction>30?'MODERATE':'LOW';
  const confidence=Math.min(96,Math.max(68,Math.round(70+Number(zone.historicalRisk||0)*.18)));
  const drivers=[['Rainfall',zone.rainfall],['Slope',zone.slope],['Soil moisture',zone.soilMoisture]].sort((a,b)=>Number(b[1]||0)-Number(a[1]||0)).slice(0,2).map(([name])=>name).join(' + ');
  $('#aiPredictedScore').textContent=prediction; $('#aiPredictedLevel').textContent=`${level} · ${zone.name}`; $('#aiPredictedLevel').className=`ai-predicted-level ${level.toLowerCase()}`; $('#aiConfidence').textContent=`${confidence}%`; $('#aiDrivers').textContent=drivers||'Current conditions'; $('#aiPredictionNote').textContent=`AI-assisted forecast for the next 24 hours, based on rainfall, slope, soil moisture, historical risk, and ground movement.`;
}
async function selectZone(zone){ selectedZone=zone; const result=await API.calculateRisk(zone); zone.riskScore=result.score; zone.level=result.level; $('#selectedZoneName').textContent=zone.name; $('#selectedScore').textContent=result.score; $('#selectedLevel').textContent=levelLabel(result.level); $('#selectedLevel').className=`risk-badge ${result.level}`; $('#selectedCoordinates').textContent=`${Number(zone.lat).toFixed(2)}Â° N, ${Number(zone.lon).toFixed(2)}Â° E`; $('#selectedExposure').textContent=`${formatNumber(zone.population)} people exposed`; $('#selectedRecommendation').textContent=zone.recommendation || 'Continue monitoring this zone.'; $('#factorList').innerHTML=FACTOR_META.map(([name,key])=>`<div class="factor-row"><div><div class="factor-name"><span>${name}</span><strong>${zone[key]||0}%</strong></div><div class="factor-track"><span style="width:${zone[key]||0}%"></span></div></div><span class="factor-value">+${Math.round((zone[key]||0)*({rainfall:.30,soilMoisture:.10,slope:.15,historicalRisk:.15,groundMovement:.10}[key]||.2))}</span></div>`).join(''); if(map)map.setView([zone.lat,zone.lon],zone.state==='Sikkim'?7:6); }
function renderAlerts(){ $('#alertList').innerHTML=alerts.map(a=>`<div class="alert-item"><i class="alert-marker ${a.level}"></i><div class="alert-copy"><strong>${a.zone}</strong><span>${a.detail}</span></div><span class="alert-time">${a.time}</span></div>`).join(''); $('#alertCount').textContent=alerts.length; $('#citizenAlerts').innerHTML=alerts.map(a=>`<div class="citizen-alert"><span class="risk-badge ${a.level}">${levelLabel(a.level)}</span><strong>${a.zone}</strong><p>${a.detail}. ${a.time}</p></div>`).join(''); renderNotifications(); }
function renderNotifications(){ const list=$('#notificationList'); if(!list)return; list.innerHTML=alerts.length?alerts.map(a=>`<div class="notification-item"><i class="${a.level}"></i><div><strong>${a.zone}</strong><span>${a.detail} · ${a.time}</span></div></div>`).join(''):'<div class="notification-empty">No active notifications.</div>'; }
function renderChart(){ const canvas=$('#riskChart'); if(typeof Chart==='undefined'||!canvas)return; if(riskChart)riskChart.destroy(); riskChart=new Chart(canvas,{type:'line',data:{labels:['03 Sep','04 Sep','05 Sep','06 Sep','07 Sep','08 Sep','09 Sep'],datasets:[{data:[42,45,49,55,62,73,84],borderColor:'#378466',backgroundColor:'rgba(55,132,102,.09)',fill:true,tension:.38,pointRadius:3,pointBackgroundColor:'#fff',pointBorderWidth:2,pointBorderColor:'#378466'},{data:[71,71,71,71,71,71,71],borderColor:'#d9b34d',borderDash:[4,4],pointRadius:0,fill:false}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{displayColors:false,callbacks:{label:context=>context.datasetIndex===0?` Risk score: ${context.raw}`:' Critical threshold'}}},scales:{x:{grid:{display:false},border:{display:false},ticks:{font:{size:9},color:'#9aa69f'}},y:{min:0,max:100,grid:{color:'#edf1ee'},border:{display:false},ticks:{stepSize:25,font:{size:9},color:'#9aa69f'}}}}}); }
function renderReports(currentReports){ $('#reportBadge').textContent=currentReports.length; $('#reportSummary').textContent=`${currentReports.length} reports`; $('#reportsTableBody').innerHTML=currentReports.length?currentReports.map(report=>`<tr><td><strong>${report.location}</strong><br><small>${report.description||'No description'}</small></td><td>${report.latitude&&report.longitude?`${Number(report.latitude).toFixed(4)}°, ${Number(report.longitude).toFixed(4)}°`:'Not provided'}</td><td>${report.submitted||report.submittedAt||'Just now'}</td><td><span class="table-pill ${report.severity==='critical'?'blocked':''}">${levelLabel(report.severity)}</span></td><td><span class="table-pill ${report.roadBlocked==='yes'?'blocked':'verified'}">${report.roadBlocked==='yes'?'Blocked':'Passable'}</span></td><td><span class="table-pill unverified">Unverified</span></td></tr>`).join(''):'<tr><td colspan="6" style="text-align:center;color:#9aa69f;padding:35px">No new reports yet. Community observations will appear here.</td></tr>'; }
function showToast(message){ const toast=$('#toast'); toast.textContent=message; toast.classList.add('show'); setTimeout(()=>toast.classList.remove('show'),3200); }
function openModal(){ const modal=$('#reportModal'); modal.classList.add('open'); modal.setAttribute('aria-hidden','false'); }
function closeModal(){ const modal=$('#reportModal'); modal.classList.remove('open'); modal.setAttribute('aria-hidden','true'); }
function repairEncoding(){ const replacements={'Â·':'·','â†’':'→','â€™':'’','â€¢':'•','âœ¦':'✦','âœ“':'✓','â—':'●','â—’':'◒','âŒ–':'⌖','âŒ':'⌁','â™§':'♧','â–£':'▣','Ã—':'×','Â°':'°'}; const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT); const nodes=[]; while(walker.nextNode())nodes.push(walker.currentNode); nodes.forEach(node=>{node.nodeValue=Object.entries(replacements).reduce((text,[bad,good])=>text.replaceAll(bad,good),node.nodeValue);}); }
const translations={
  en:{command:'Command center',citizen:'Citizen safety',reports:'Incident reports',workspace:'Workspace',system:'System',map:'North Eastern India · risk points',critical:'CRITICAL HIGHLIGHTED',location:'⌖ My location',logout:'Logout',notifications:'Notifications',markRead:'Mark read',updated:'Updated just now',welcome:'Welcome back',signIn:'Sign in',demo:'Continue as demo user',activeAlerts:'Active alerts',sensor:'Sensor health',weather:'Monsoon watch',riskTrend:'Regional risk · last 7 days'},
  hi:{command:'कमांड सेंटर',citizen:'नागरिक सुरक्षा',reports:'घटना रिपोर्ट',workspace:'कार्यस्थल',system:'सिस्टम',map:'पूर्वोत्तर भारत · जोखिम बिंदु',critical:'गंभीर जोखिम',location:'⌖ मेरा स्थान',logout:'लॉग आउट',notifications:'सूचनाएं',markRead:'पढ़ा हुआ चिह्नित करें',updated:'अभी अपडेट किया गया',welcome:'वापसी पर स्वागत है',signIn:'साइन इन',demo:'डेमो उपयोगकर्ता के रूप में जारी रखें',activeAlerts:'सक्रिय चेतावनियां',sensor:'सेंसर स्थिति',weather:'मानसून निगरानी',riskTrend:'क्षेत्रीय जोखिम · पिछले 7 दिन'},
  bn:{command:'কমান্ড সেন্টার',citizen:'নাগরিক নিরাপত্তা',reports:'ঘটনা রিপোর্ট',workspace:'কর্মক্ষেত্র',system:'সিস্টেম',map:'উত্তর-পূর্ব ভারত · ঝুঁকি পয়েন্ট',critical:'গুরুতর ঝুঁকি',location:'⌖ আমার অবস্থান',logout:'লগ আউট',notifications:'বিজ্ঞপ্তি',markRead:'পঠিত হিসেবে চিহ্নিত করুন',updated:'এইমাত্র আপডেট হয়েছে',welcome:'আবার স্বাগতম',signIn:'সাইন ইন',demo:'ডেমো ব্যবহারকারী হিসেবে চালিয়ে যান',activeAlerts:'সক্রিয় সতর্কতা',sensor:'সেন্সর স্বাস্থ্য',weather:'বর্ষা পর্যবেক্ষণ',riskTrend:'আঞ্চলিক ঝুঁকি · গত ৭ দিন'},
  as:{command:'কমাণ্ড চেণ্টাৰ',citizen:'নাগৰিক সুৰক্ষা',reports:'ঘটনা প্ৰতিবেদন',workspace:'কৰ্মক্ষেত্ৰ',system:'ছিষ্টেম',map:'উত্তৰ-পূব ভাৰত · বিপদৰ বিন্দু',critical:'গুৰুতৰ বিপদ',location:'⌖ মোৰ অৱস্থান',logout:'লগ আউট',notifications:'জাননী',markRead:'পঢ়া বুলি চিহ্নিত কৰক',updated:'এইমাত্ৰ আপডেট কৰা হৈছে',welcome:'পুনৰ স্বাগতম',signIn:'ছাইন ইন',demo:'ডেমো ব্যৱহাৰী হিচাপে আগবাঢ়ক',activeAlerts:'সক্ৰিয় সতৰ্কবাণী',sensor:'চেন্সৰ স্বাস্থ্য',weather:'বৰষুণ নিৰীক্ষণ',riskTrend:'আঞ্চলিক বিপদ · যোৱা ৭ দিন'}
};
function applyLanguage(code){ const t=translations[code]||translations.en; const nav={authority:t.command,citizen:t.citizen,reports:t.reports}; Object.entries(nav).forEach(([view,text])=>{const button=$(`.nav-item[data-view="${view}"]`); if(button)button.lastChild.nodeValue=`${text}`;}); $('#breadcrumbCurrent').textContent=t.command; $('.map-panel h2').textContent=t.map; $('.map-panel .risk-badge').textContent=t.critical; $('#locateMe').textContent=t.location; $('#logoutButton').textContent=t.logout; $('.notification-panel-header strong').textContent=t.notifications; $('#clearNotifications').textContent=t.markRead; $('#lastUpdatedText').textContent=t.updated; $('.alerts-panel h2').childNodes[0].nodeValue=`${t.activeAlerts} `; $('.sensor-panel h2').textContent=t.sensor; $('.weather-panel h2').textContent=t.weather; $('.chart-panel h2').textContent=t.riskTrend; $('#loginScreen h1').textContent=t.welcome; $('#loginForm button[type="submit"]').childNodes[0].nodeValue=`${t.signIn} `; $('#demoLogin').textContent=t.demo; sessionStorage.setItem('landsafe-language',code); }
function updateIndiaDateTime(){ const now=new Date(); const dateFormatter=new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',weekday:'long',day:'2-digit',month:'long',year:'numeric'}); const timeFormatter=new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',hour12:false}); const date=$('#dashboardDate'); const last=$('#lastUpdatedText'); if(date)date.textContent=`${dateFormatter.format(now).toUpperCase()} · ${timeFormatter.format(now)} IST`; if(last)last.textContent=`Updated ${timeFormatter.format(now)} IST`; }
function updateLiveStatus(state='synced'){ const connection=$('#liveConnectionStatus'); const sync=$('#liveSyncStatus'); const connectionDot=$('#liveConnectionDot'); const syncDot=$('#liveSyncDot'); if(!connection||!sync)return; if(state==='error'){connection.textContent='Live connection unavailable';sync.textContent='Showing last known data';connectionDot.className='status-dot warn';syncDot.className='status-dot warn';} else if(liveMode){connection.textContent='Live connection online';sync.textContent='Live data synced';connectionDot.className='status-dot online';syncDot.className='status-dot online';} else {connection.textContent='Demo connection online';sync.textContent='Local fallback data';connectionDot.className='status-dot warn';syncDot.className='status-dot warn';} updateIndiaDateTime(); }
async function refreshLive(){ const previousId=selectedZone.id; const nextZones=await API.getZones(); const nextAlerts=await API.getAlerts(); const nextReports=await API.getReports(); zones=nextZones; alerts=nextAlerts; reports=nextReports; buildMetrics(zones,reports); renderAlerts(); renderReports(reports); renderMapLabels(); renderMarkers(); const nextSelected=zones.find(zone=>zone.id===previousId)||zones[0]; await selectZone(nextSelected); updateLiveStatus('synced'); }
async function boot(){ [zones,reports,alerts]=await Promise.all([API.getZones(),API.getReports(),API.getAlerts()]); buildMetrics(zones,reports); renderAlerts(); renderReports(reports); initMap(); renderChart(); await selectZone(zones[0]); updateIndiaDateTime(); updateLiveStatus('synced'); repairEncoding(); setInterval(()=>{updateIndiaDateTime();refreshLive().catch(()=>{updateLiveStatus('error');showToast('Live refresh unavailable · keeping the last update')})},30000); }
$$('.nav-item').forEach(button=>button.addEventListener('click',()=>{const view=button.dataset.view;$$('.nav-item').forEach(item=>item.classList.toggle('active',item===button));$$('.view').forEach(item=>item.classList.remove('active-view'));$(`#${view}View`).classList.add('active-view');$('#breadcrumbCurrent').textContent=view==='authority'?'Command center':view==='citizen'?'Citizen safety':'Incident reports';if(view==='authority'&&map)setTimeout(()=>map.invalidateSize(true),100);}));
$$('.filter-button[data-filter]').forEach(button=>button.addEventListener('click',()=>{$$('.filter-button[data-filter]').forEach(item=>item.classList.remove('active'));button.classList.add('active');renderMarkers(button.dataset.filter);}));
$('#refreshData').addEventListener('click',async()=>{ const button=$('#refreshData'); button.disabled=true; button.textContent='↻ Refreshing…'; try { await refreshLive(); showToast(liveMode?'Live data refreshed':'Demo data refreshed · backend unavailable'); } catch { updateLiveStatus('error'); showToast('Refresh failed · keeping the last update'); } finally { button.disabled=false; button.textContent='↻ Refresh data'; } });
const notificationButton=$('#notificationButton');
const notificationPanel=$('#notificationPanel');
if(notificationButton&&notificationPanel){ notificationButton.addEventListener('click',event=>{ event.stopPropagation(); const open=!notificationPanel.classList.contains('open'); notificationPanel.classList.toggle('open',open); notificationPanel.setAttribute('aria-hidden',String(!open)); notificationButton.setAttribute('aria-expanded',String(open)); }); $('#clearNotifications')?.addEventListener('click',()=>{ alerts=[]; renderAlerts(); notificationPanel.classList.remove('open'); notificationButton.setAttribute('aria-expanded','false'); }); document.addEventListener('click',event=>{ if(!notificationPanel.contains(event.target)&&event.target!==notificationButton){ notificationPanel.classList.remove('open'); notificationButton.setAttribute('aria-expanded','false'); } }); }
const NER_STATE_CENTERS={'Sikkim':[27.55,88.50],'Arunachal Pradesh':[28.10,94.00],'Assam':[26.20,92.90],'Meghalaya':[25.55,91.35],'Nagaland':[26.05,94.35],'Manipur':[24.75,93.85],'Mizoram':[23.35,92.75],'Tripura':[23.75,91.70]};
function getMapSearchMatches(query){
  const text=query.trim().toLowerCase(); if(!text)return [];
  const stateMatches=Object.entries(NER_STATE_CENTERS).filter(([name])=>name.toLowerCase().includes(text)).map(([name,[lat,lon]])=>({name,state:name,lat,lon}));
  const placeMatches=zones.filter(zone=>NORTH_EAST_STATES.has(zone.state)&&`${zone.name} ${zone.state}`.toLowerCase().includes(text)).map(zone=>({name:zone.name,state:zone.state,lat:Number(zone.lat),lon:Number(zone.lon),zone}));
  return [...placeMatches,...stateMatches].filter((item,index,array)=>array.findIndex(other=>other.name===item.name)===index).slice(0,6);
}
function renderMapSearchResults(matches){ const results=$('#mapSearchResults'); if(!results)return; results.innerHTML=matches.map((item,index)=>`<button type="button" role="option" data-index="${index}"><strong>${item.name}</strong><small>${item.state}</small></button>`).join(''); results.classList.toggle('open',matches.length>0); results.querySelectorAll('[data-index]').forEach(button=>button.addEventListener('click',()=>zoomToMapPlace(matches[Number(button.dataset.index)]))); }
async function zoomToMapPlace(place){ if(!place||!map)return; $('#mapSearchInput').value=place.name; $('#mapSearchResults')?.classList.remove('open'); if(place.zone)await selectZone(place.zone); map.setView([place.lat,place.lon],place.zone?9:7); showToast(`Map focused on ${place.name}`); }
const mapSearchForm=$('#mapSearchForm');
const mapSearchInput=$('#mapSearchInput');
if(mapSearchForm&&mapSearchInput){ mapSearchInput.addEventListener('input',()=>renderMapSearchResults(getMapSearchMatches(mapSearchInput.value))); mapSearchForm.addEventListener('submit',async event=>{event.preventDefault();const matches=getMapSearchMatches(mapSearchInput.value);if(!matches.length){renderMapSearchResults([]);showToast('No North Eastern place found');return;}await zoomToMapPlace(matches[0]);}); document.addEventListener('click',event=>{if(!mapSearchForm.contains(event.target))$('#mapSearchResults')?.classList.remove('open');}); }
const locateButton=$('#locateMe');
if(locateButton) locateButton.addEventListener('click',locateUser);
$('#runScenario').addEventListener('click',()=>{selectZone({...selectedZone,rainfall:100,sevenDayRainfall:96,soilMoisture:92,groundMovement:88});showToast('Critical rainfall scenario applied to selected zone');});
$('#openReportModal').addEventListener('click',openModal); $('#citizenReportButton').addEventListener('click',openModal); $('#closeReportModal').addEventListener('click',closeModal); $('#reportModal').addEventListener('click',event=>{if(event.target.id==='reportModal')closeModal();});
$('#reportLocationButton')?.addEventListener('click',()=>{ if(!navigator.geolocation){showToast('Location is not supported by this browser');return;} const button=$('#reportLocationButton'); button.disabled=true; button.textContent='Locating…'; navigator.geolocation.getCurrentPosition(position=>{ $('#reportLatitude').value=position.coords.latitude.toFixed(6); $('#reportLongitude').value=position.coords.longitude.toFixed(6); button.disabled=false; button.textContent='⌖ Use my current location'; showToast('Report coordinates added'); },()=>{button.disabled=false;button.textContent='⌖ Use my current location';showToast('Could not read your location');},{enableHighAccuracy:true,timeout:10000,maximumAge:30000}); });
$('#reportForm').addEventListener('submit',async event=>{event.preventDefault();const data=new FormData(event.target);const report={location:data.get('location'),latitude:data.get('latitude')||null,longitude:data.get('longitude')||null,severity:data.get('severity'),roadBlocked:data.get('roadBlocked'),description:data.get('description'),submitted:'Just now',status:'unverified'};try{await API.saveReport(report);reports=await API.getReports();renderReports(reports);buildMetrics(zones,reports);closeModal();event.target.reset();showToast('Report submitted to the response desk');}catch{showToast('Could not submit report · please try again');}});
window.addEventListener('resize',()=>{if(map)map.invalidateSize(true);});
const loginScreen=$('#loginScreen');
const loginForm=$('#loginForm');
if(sessionStorage.getItem('landsafe-authenticated')==='true') loginScreen?.classList.add('hidden');
const languageSelect=$('#languageSelect');
if(languageSelect){ languageSelect.value=sessionStorage.getItem('landsafe-language')||'en'; languageSelect.addEventListener('change',event=>applyLanguage(event.target.value)); applyLanguage(languageSelect.value); }
loginForm?.addEventListener('submit',event=>{ event.preventDefault(); const email=$('#loginEmail').value.trim(); const password=$('#loginPassword').value; const error=$('#loginError'); if(!email||password.length<4){ error.textContent='Enter a valid email and a password with at least 4 characters.'; return; } sessionStorage.setItem('landsafe-authenticated','true'); sessionStorage.setItem('landsafe-user',email); loginScreen.classList.add('hidden'); showToast(`Welcome, ${email}`); if(map) setTimeout(()=>map.invalidateSize(true),100); });
$('#demoLogin')?.addEventListener('click',()=>{ sessionStorage.setItem('landsafe-authenticated','true'); sessionStorage.setItem('landsafe-user','Demo user'); loginScreen?.classList.add('hidden'); showToast('Welcome, Demo user'); if(map) setTimeout(()=>map.invalidateSize(true),100); });
$('#logoutButton')?.addEventListener('click',()=>{ sessionStorage.removeItem('landsafe-authenticated'); sessionStorage.removeItem('landsafe-user'); loginScreen?.classList.remove('hidden'); $('#loginForm')?.reset(); showToast('You have been logged out'); });
/* GIS map engine: OpenLayers replaces the earlier Leaflet implementation.
function olPointStyle(color, radius, label=''){
  return new ol.style.Style({image:new ol.style.Circle({radius,fill:new ol.style.Fill({color}),stroke:new ol.style.Stroke({color:'#fff',width:2})}),text:label?new ol.style.Text({text:label,offsetX:10,textAlign:'left',font:'600 11px DM Sans',fill:new ol.style.Fill({color:'#30463b'}),stroke:new ol.style.Stroke({color:'#fff',width:3})}):undefined});
}
function initMap(){
  if(typeof ol==='undefined'){ $('#riskMap').innerHTML='<div class="map-fallback">GIS map unavailable offline.<br><strong>OpenLayers could not be loaded.</strong></div>'; return; }
  const extent=ol.proj.transformExtent([88,21.5,97.8,29.8],'EPSG:4326','EPSG:3857');
  const view=new ol.View({center:ol.proj.fromLonLat([93,25.5]),zoom:6,minZoom:6,maxZoom:12,extent,constrainOnlyCenter:false});
  const baseLayer=new ol.layer.Tile({source:new ol.source.OSM(),opacity:.98});
  markerLayer=new ol.layer.Vector({source:new ol.source.Vector(),zIndex:70});
  userLocationLayer=new ol.layer.Vector({source:new ol.source.Vector(),zIndex:80});
  mapLabelLayer=new ol.layer.Vector({source:new ol.source.Vector(),zIndex:65});
  map=new ol.Map({target:'riskMap',layers:[baseLayer,mapLabelLayer,markerLayer,userLocationLayer],view,controls:ol.control.defaults({zoom:true,rotate:false,attribution:true})});
  const legend=document.createElement('div'); legend.className='risk-map-legend ol-risk-map-legend'; legend.innerHTML='<strong>GIS risk level</strong><button type="button" data-risk="all">All points</button><button type="button" data-risk="critical"><i class="legend-swatch critical"></i>Critical</button><button type="button" data-risk="high"><i class="legend-swatch high"></i>High</button><button type="button" data-risk="moderate"><i class="legend-swatch moderate"></i>Moderate</button><button type="button" data-risk="low"><i class="legend-swatch low"></i>Low</button>';
  document.getElementById('riskMap').appendChild(legend);
  legend.querySelectorAll('[data-risk]').forEach(button=>button.addEventListener('click',()=>{legend.querySelectorAll('[data-risk]').forEach(item=>item.classList.remove('active'));button.classList.add('active');mapRiskFilter=button.dataset.risk;renderMarkers(mapRiskFilter);}));
  legend.querySelector('[data-risk="all"]').classList.add('active');
  map.on('singleclick',event=>{const feature=map.forEachFeatureAtPixel(event.pixel,item=>item);const zone=feature&&feature.get('zone');if(zone)selectZone(zone);});
  renderMapLabels(); renderMarkers(); loadNorthEastIndiaBoundary();
  requestAnimationFrame(()=>map.updateSize());
}
function renderMapLabels(){
  if(!mapLabelLayer||typeof ol==='undefined')return;
  const source=mapLabelLayer.getSource(); source.clear();
  const stateCenters={'Sikkim':[27.55,88.50],'Arunachal Pradesh':[28.10,94.00],'Assam':[26.20,92.90],'Meghalaya':[25.55,91.35],'Nagaland':[26.05,94.35],'Manipur':[24.75,93.85],'Mizoram':[23.35,92.75],'Tripura':[23.75,91.70]};
  Object.entries(stateCenters).forEach(([name,coords])=>{const feature=new ol.Feature(new ol.geom.Point(ol.proj.fromLonLat(coords)));feature.setStyle(new ol.style.Style({text:new ol.style.Text({text:name,font:'700 12px Manrope',fill:new ol.style.Fill({color:'#15563f'}),backgroundFill:new ol.style.Fill({color:'rgba(255,255,255,.9)'}),padding:[4,7,4,7],offsetY:-4,stroke:new ol.style.Stroke({color:'rgba(23,107,77,.35)',width:1})})}));source.addFeature(feature);});
  const seen=new Set(); zones.filter(zone=>NORTH_EAST_STATES.has(zone.state)).forEach(zone=>{const place=String(zone.name||zone.state).split(' · ')[0];if(seen.has(place))return;seen.add(place);const feature=new ol.Feature(new ol.geom.Point(ol.proj.fromLonLat([Number(zone.lon),Number(zone.lat)])));feature.setStyle(new ol.style.Style({text:new ol.style.Text({text:place,font:'600 10px DM Sans',offsetX:10,textAlign:'left',fill:new ol.style.Fill({color:'#3c5046'}),stroke:new ol.style.Stroke({color:'#fff',width:3})})}));source.addFeature(feature);});
}
async function loadNorthEastIndiaBoundary(){
  try{
    const response=await fetch('https://raw.githubusercontent.com/geohacker/india/master/state/india_state.geojson'); if(!response.ok)throw new Error(); const data=await response.json(); const selected=data.features.filter(feature=>Object.values(feature.properties||{}).some(value=>NORTH_EAST_STATES.has(String(value)))); if(!selected.length)return;
    const format=new ol.format.GeoJSON(); const features=format.readFeatures({type:'FeatureCollection',features:selected},{featureProjection:'EPSG:3857'});
    const boundaryLayer=new ol.layer.Vector({source:new ol.source.Vector({features}),zIndex:45,style:new ol.style.Style({stroke:new ol.style.Stroke({color:'#176b4d',width:2.5}),fill:new ol.style.Fill({color:'rgba(217,239,226,.28)'})})}); map.getLayers().insertAt(1,boundaryLayer);
    const rings=[]; features.forEach(feature=>{const geometry=feature.getGeometry();if(geometry instanceof ol.geom.Polygon)rings.push(geometry.getCoordinates()[0]);if(geometry instanceof ol.geom.MultiPolygon)geometry.getCoordinates().forEach(polygon=>rings.push(polygon[0]));});
    const outer=[ol.proj.fromLonLat([87.2,20.8]),ol.proj.fromLonLat([99.2,20.8]),ol.proj.fromLonLat([99.2,31.2]),ol.proj.fromLonLat([87.2,31.2]),ol.proj.fromLonLat([87.2,20.8])];
    const mask=new ol.Feature(new ol.geom.Polygon([outer,...rings])); const maskLayer=new ol.layer.Vector({source:new ol.source.Vector({features:[mask]}),zIndex:35,style:new ol.style.Style({fill:new ol.style.Fill({color:'rgba(245,247,244,.78)'})})}); map.getLayers().insertAt(1,maskLayer); renderMapLabels();
  }catch{ }
}
function renderMarkers(filter=mapRiskFilter){
  if(!markerLayer||typeof ol==='undefined')return; const source=markerLayer.getSource();source.clear();const colors={critical:'#c9524b',high:'#da8d32',moderate:'#c6a136',low:'#4e9d70'};
  zones.filter(zone=>NORTH_EAST_STATES.has(zone.state)).forEach(zone=>{const risk=zone.riskScore||estimateRisk(zone);const critical=(zone.level||'moderate')==='critical'||risk>70;const riskLevel=critical?'critical':(zone.level||'moderate');if(filter!=='all'&&riskLevel!==filter)return;const feature=new ol.Feature(new ol.geom.Point(ol.proj.fromLonLat([Number(zone.lon),Number(zone.lat)])));feature.set('zone',zone);feature.setStyle(olPointStyle(colors[riskLevel]||colors.moderate,critical?10:8));source.addFeature(feature);});
}
function locateUser(){
  if(!navigator.geolocation){showToast('Live location is not supported by this browser');return;} const button=$('#locateMe');button.disabled=true;button.textContent='Locating…';
  navigator.geolocation.getCurrentPosition(position=>{const {latitude,longitude,accuracy}=position.coords;const withinNorthEast=latitude>=21.5&&latitude<=29.8&&longitude>=88&&longitude<=97.8;const source=userLocationLayer.getSource();source.clear();const point=new ol.Feature(new ol.geom.Point(ol.proj.fromLonLat([longitude,latitude])));point.setStyle(olPointStyle('#3da5f5',9));const accuracyFeature=new ol.Feature(new ol.geom.Circle(ol.proj.fromLonLat([longitude,latitude]),accuracy));accuracyFeature.setStyle(new ol.style.Style({fill:new ol.style.Fill({color:'rgba(61,165,245,.12)'}),stroke:new ol.style.Stroke({color:'#3da5f5',width:1})}));source.addFeatures([accuracyFeature,point]);map.getView().animate({center:ol.proj.fromLonLat([longitude,latitude]),zoom:withinNorthEast?9:6,duration:500});checkNearbyRisk(latitude,longitude);showToast(withinNorthEast?'Live location enabled on the North Eastern GIS map':'Your location is outside the North Eastern region');button.disabled=false;button.textContent='⌖ My location';},error=>{const message=error.code===1?'Location permission was denied':error.code===2?'Location is unavailable':'Location request timed out';showToast(message);button.disabled=false;button.textContent='⌖ My location';},{enableHighAccuracy:true,timeout:10000,maximumAge:30000});
}
function checkNearbyRisk(latitude,longitude){const nearby=zones.map(zone=>{const risk=zone.riskScore||estimateRisk(zone);return {...zone,risk,distance:distanceKm(latitude,longitude,Number(zone.lat),Number(zone.lon))};}).filter(zone=>NORTH_EAST_STATES.has(zone.state)&&zone.distance<=25&&zone.risk>=51).sort((a,b)=>a.distance-b.distance)[0];if(!nearby)return;const critical=nearby.risk>=71;const message=`${critical?'CRITICAL':'HIGH'} RISK NEARBY: ${nearby.name} · ${nearby.distance.toFixed(1)} km away`;showToast(message);}
async function selectZone(zone){selectedZone=zone;const result=await API.calculateRisk(zone);zone.riskScore=result.score;zone.level=result.level;$('#selectedZoneName').textContent=zone.name;$('#selectedScore').textContent=result.score;$('#selectedLevel').textContent=levelLabel(result.level);$('#selectedLevel').className=`risk-badge ${result.level}`;$('#selectedCoordinates').textContent=`${Number(zone.lat).toFixed(2)}° N, ${Number(zone.lon).toFixed(2)}° E`;$('#selectedExposure').textContent=`${formatNumber(zone.population)} people exposed`;$('#selectedRecommendation').textContent=zone.recommendation||'Continue monitoring this zone.';$('#factorList').innerHTML=FACTOR_META.map(([name,key])=>`<div class="factor-row"><div><div class="factor-name"><span>${name}</span><strong>${zone[key]||0}%</strong></div><div class="factor-track"><span style="width:${zone[key]||0}%"></span></div></div><span class="factor-value">+${Math.round((zone[key]||0)*({rainfall:.30,soilMoisture:.10,slope:.15,historicalRisk:.15,groundMovement:.10}[key]||.2))}</span></div>`).join('');if(map)map.getView().animate({center:ol.proj.fromLonLat([Number(zone.lon),Number(zone.lat)]),zoom:zone.state==='Sikkim'?7:6,duration:450});}
*/
const dashboardSelectZone=selectZone;
selectZone=async zone=>{renderAiPrediction(zone);return dashboardSelectZone(zone);};
boot();
